resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio

variables:
  BuildConfiguration: 'Release'
  RunIntegrationTests: 'true'
steps:
- task: NuGetCommand@2
  displayName: 'NuGet restore'


- task: VSBuild@1
  displayName: 'Build and package API'
  inputs:
    solution: Api/Api.csproj

    msbuildArgs: '/p:DeployOnBuild=true /p:PublishProfile="Package"'

    configuration: '$(BuildConfiguration)'


- task: VSBuild@1
  displayName: 'Build integration tests'
  inputs:
    solution: Api.IntegrationTests/Api.IntegrationTests.csproj

    configuration: '$(BuildConfiguration)'


- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Visual Studio Test Platform Installer'
  inputs:
    versionSelector: latestStable


- task: VSTest@2
  displayName: 'Run integration tests'
  inputs:
    testAssemblyVer2: |
     **/*IntegrationTests.dll
     !**\*TestAdapter.dll
     !**\obj\**

    vsTestVersion: toolsInstaller

  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['RunIntegrationTests'], 'true')))

- task: CopyFiles@2
  displayName: 'Copy package to staging'
  inputs:
    SourceFolder: 'Api\bin\$(BuildConfiguration)\Publish'

    Contents: '**/*'

    TargetFolder: '$(Build.ArtifactStagingDirectory)/$(BuildConfiguration)/Api'

    CleanTargetFolder: true

    OverWrite: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

